name: TOLEK SuperDoc Monitor

on:
  schedule:
    - cron: '*/10 * * * *'     # на всеки 10 минути
  workflow_dispatch:           # позволява ръчно пускане

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install playwright requests
          playwright install --with-deps chromium

      - name: Run monitor
      
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
        run: python monitor.py
